name: bun

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --check-files

      - name: Run linting
        run: bun lint

      - name: Check images
        run: node ./check-images.js

      - name: Run build
        run: bun run build
