name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: generate 
